### ISSUE TITLE
Script can look for binary in the wrong cache directory

### ISSUE THREAD

**Issue by psirenny** [jahed/node-terraform#11] opened 2021-01-29 17:34 UTC
The issue is most apparent in monorepos, where the `.cache` directory is located in the project's root `node modules` directory. Here's an example project file structure:

* root:
  * node_modules:
    * .cache:
      * @jahed/terraform/terraform-v0.14.5 
  * packages:
    * child 1:
      * node_modules:
        * @jahed/terraform/bin/terraform.js
    * child 2:
      * node_modules::
        * @jahed/terraform/bin/terraform.js

When terraform.js is executed it looks for the binary at this path:
```
/root/packages/child/node_modules/.cache/@jahed/terraform/terraform-v0.14.5
```

Instead of:

```
/root/node_modules/.cache/@jahed/terraform/terraform-v0.14.5
```

BTW, thanks for maintaining this package and going through the trouble of keeping the version in sync with terraform. It's much appreciated.

**Comment by jahed** [comment] 2021-01-29 18:50
I use @jahed/terraform for my own monorepos and it seems to be fine. Can you explain your project workflow? Which command did you run to install Terraform and which do you use to execute it?

For example, I do the following:

```bash
# Install
yarn workspace @jahed/website add @jahed/terraform

# Execute
yarn workspace @jahed/website terraform apply
```

This can be repeated for any workspace inside the monorepo so you can have different versions of Terraform across different workspaces. It'll install the cached executable inside the workspace's cache rather than root.

**Comment by psirenny** [comment] 2021-01-29 19:11
The terraform command works well when executed from the root (like you have above). It only fails when the current working directory is the child. For example:

```sh
cd projects/@jahed/website
npx terraform
```

You could make the case that that's the expected behavior. If so, I can close this issue. Although, other packages -- such as babel -- do handle this case.

**Comment by jahed** [comment] 2021-01-29 20:37
The above example does work for me as the `install` (or `add` for yarn) is done at the current directory so the cache will be there rather than at the root.

```bash
# Continuing from my example
$ cd packages/website
$ yarn terraform --version # or npx terraform --version
Terraform v0.14.5
```

By Babel, do you mean [the cache implementation](https://github.com/babel/babel/blob/98aa72ca74631dc80e0a9e56a3a105c139b152a4/packages/babel-register/src/cache.js)? It uses the same package (`find-cache-dir`) which will find the closest `package.json` (going up directories) and use the `node_modules/.cache` in that directory.

Can you provide a reproducible repository? That'll help me decide if it's expected behaviour or not and provide a test case to confirm a fix. Otherwise, we can agree it's a `wontfix` for now.

**Closed** 2021-02-01 18:08 UTC
Labels: wontfix

**Comment by jahed** [comment] 2021-09-04 15:01
Just letting you know, the issue here should be resolved via https://github.com/jahed/node-terraform/commit/491b8c0967a75f4bae8a66b6f5a6a8cc6158bb0f

Essentially, Terraform is no longer downloaded during `npm install` (or `yarn install`). This is because the install hooks are unreliable. Yarn especially does not consistently call a dependency's `install` script during a `yarn install` so it's possible that the cache goes out of sync.

Now if it's looking for a Terraform executable in any `node_modules` directory, and it's not there, it will download it there automatically before attempting to call Terraform.

**Comment by psirenny** [comment] 2021-09-04 15:13
Awesome, thanks! Yea, I've found that working with the install/prepublish/preinstall, etc. scripts is a nightmare. Definitely more reliable to install on demand.
